server:
  port: 8082


spring:
  application:
    name: STUDENT-WRITE-SERVICE
#  zipkin:
#    base-url: http://127.0.0.1:9411

  cloud:
    config:
      enabled: true
      uri: http://localhost:9292
